name: Run Test

on:
  workflow_call:

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '7.0.x'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore neo-express.sln

    - name: Format
      run: |
        dotnet format neo-express.sln --verify-no-changes --no-restore --verbosity diagnostic

  build:
    needs: [format]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.1
      id: nbgv

    - name: Restore
      run: dotnet restore neo-express.sln

    - name: Build
      run: dotnet build neo-express.sln --configuration ${{ env.CONFIGURATION }} --no-restore --verbosity normal

    - name: Test
      run: dotnet test neo-express.sln --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

    - name: Pack for Install
      run: dotnet pack neo-express.sln --configuration ${{ env.CONFIGURATION }} --output ./out --no-build --verbosity normal

    - name: Install epicchain tool
      run: dotnet tool install --add-source ./out --verbosity normal --global --prerelease neo.express

    - name: Test Create Command (epicchain)
      run: epicchain create

    - name: Test Checkpoint Command (offline) (epicchain)
      run: epicchain checkpoint create checkpoints/init --force

    - name: Test Policy Command (offline) (epicchain)
      run: |
        epicchain policy get --rpc-uri mainnet --json > mainnet-policy.json
        epicchain policy sync mainnet-policy --account genesis

    - name: Test Wallet Command (epicchain)
      run: |
        epicchain wallet create bob

    - name: Test Transfer Command (offline) (epicchain)
      run: |
        epicchain transfer 10000 gas genesis node1
        epicchain transfer 10000 gas genesis bob

    - name: Test Run Command (online) (epicchain)
      timeout-minutes: 1
      run: epicchain run --seconds-per-block 3 --discard &

    - name: Test Transfer Command (online) (epicchain)
      run: |
        epicchain transfer 10000 gas genesis node1
        epicchain transfer 10000 gas genesis bob

    - name: Test Stop Command (online) (epicchain)
      run: epicchain stop --all
